-- MySQL Script generated by MySQL Workbench
-- Tue Oct 24 11:29:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jejuplus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jejuplus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jejuplus` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `jejuplus` ;

-- -----------------------------------------------------
-- Table `jejuplus`.`tb_level`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_level` (
  `level_id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`level_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jejuplus`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `level_id` INT NULL DEFAULT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(5) NOT NULL,
  `last_name` VARCHAR(10) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `is_kakao` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `level_id` (`level_id` ASC) VISIBLE,
  CONSTRAINT `tb_user_ibfk_1`
    FOREIGN KEY (`level_id`)
    REFERENCES `jejuplus`.`tb_level` (`level_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jejuplus`.`tb_payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `tid` VARCHAR(200) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `tb_payment_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jejuplus`.`tb_user` (`user_id`)
    ON DELETE SET NULL
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jejuplus`.`tb_air`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_air` (
  `air_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `payment_id` INT NOT NULL,
  `dep_pland_time` VARCHAR(50) NOT NULL,
  `arr_pland_time` VARCHAR(50) NOT NULL,
  `airline_nm` VARCHAR(30) NOT NULL,
  `arr_airport_nm` VARCHAR(30) NOT NULL,
  `dep_airport_nm` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`air_id`),
  INDEX `payment_id` (`payment_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `tb_air_ibfk_1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `jejuplus`.`tb_payment` (`payment_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `tb_air_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `jejuplus`.`tb_user` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jejuplus`.`tb_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_category` (
  `content_type_id` VARCHAR(50) NOT NULL,
  `category_name` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`content_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jejuplus`.`tb_place`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_place` (
  `place_id` INT NOT NULL AUTO_INCREMENT,
  `content_type_id` VARCHAR(50) NOT NULL,
  `addr1` VARCHAR(50) NOT NULL,
  `addr2` VARCHAR(50) NOT NULL,
  `content_id` VARCHAR(50) NOT NULL,
  `firstimage` VARCHAR(255) NOT NULL,
  `firstimage2` VARCHAR(255) NOT NULL,
  `mapx` VARCHAR(50) NOT NULL,
  `mapy` VARCHAR(50) NOT NULL,
  `tel` VARCHAR(30) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `overview` TEXT NOT NULL,
  `place_recommend` INT NULL DEFAULT NULL,
  PRIMARY KEY (`place_id`),
  UNIQUE INDEX `content_type_id` (`content_type_id` ASC) VISIBLE,
  CONSTRAINT `tb_place_ibfk_1`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `jejuplus`.`tb_category` (`content_type_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jejuplus`.`tb_favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_favorite` (
  `favorite_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `place_id` INT NOT NULL,
  PRIMARY KEY (`favorite_id`),
  INDEX `place_id` (`place_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `tb_favorite_ibfk_1`
    FOREIGN KEY (`place_id`)
    REFERENCES `jejuplus`.`tb_place` (`place_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tb_favorite_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `jejuplus`.`tb_user` (`user_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jejuplus`.`tb_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_schedule` (
  `schedule_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NOT NULL,
  PRIMARY KEY (`schedule_id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `tb_schedule_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jejuplus`.`tb_user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jejuplus`.`tb_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `place_id` INT NOT NULL,
  `schedule_id` INT NOT NULL,
  `item_memo` TEXT NULL DEFAULT NULL,
  `item_date` DATE NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `place_id` (`place_id` ASC) VISIBLE,
  INDEX `schedule_id` (`schedule_id` ASC) VISIBLE,
  CONSTRAINT `tb_item_ibfk_1`
    FOREIGN KEY (`place_id`)
    REFERENCES `jejuplus`.`tb_place` (`place_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tb_item_ibfk_2`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `jejuplus`.`tb_schedule` (`schedule_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jejuplus`.`tb_promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_promotion` (
  `promotion_id` INT NOT NULL AUTO_INCREMENT,
  `place_id` INT NOT NULL,
  `start_date` TIMESTAMP NOT NULL,
  `end_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`promotion_id`),
  INDEX `place_id` (`place_id` ASC) VISIBLE,
  CONSTRAINT `tb_promotion_ibfk_1`
    FOREIGN KEY (`place_id`)
    REFERENCES `jejuplus`.`tb_place` (`place_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jejuplus`.`tb_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jejuplus`.`tb_review` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `place_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `review_content` TEXT NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `review_recommend` INT NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `place_id` (`place_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `tb_review_ibfk_1`
    FOREIGN KEY (`place_id`)
    REFERENCES `jejuplus`.`tb_place` (`place_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `tb_review_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `jejuplus`.`tb_user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
